### ISSUE TITLE
core - 공통 컴포넌트 - 하단 Nav bar

### ISSUE THREAD

**Issue by sooje0ng** [Mews-MIS/Mews-Client#12]
## IssueName
> core - 공통 컴포넌트 - 하단 Nav bar

## Description
> 공통 컴포넌트 중 하단 Nav bar 제작

## Todo
- [x] 메인 , 뉴스, 학사일정, 마이페이지 버튼 첨부
- [x] 각 버튼 클릭 시 색 변화기능 추가
- [x] 각 버튼 클릭 시 라우팅 임시 추가

## ETC
메인, 뉴스, 학사일정, 마이페이지 제작 시 라우팅은 해당 url로 수정되어야 함
