### ISSUE TITLE
뉴스 페이지 - 게시글 세부 

### ISSUE THREAD

**Issue by Dahyeonni** [Mews-MIS/Mews-Client#40]
## IssueName
뉴스 페이지 - 게시글 세부

## Description
> 이슈에 대한 간단한 설명을 작성해주세요.

## Todo
- [x] 뉴스 화면 레이아웃
- [x] 좋아요, 구독, 링크 아이콘 
- [x] 댓글 임시 레이아웃

## ETC
기타 참고사항
