### ISSUE TITLE
core - 공통 컴포넌트 - contentRow

### ISSUE THREAD

**Issue by xilucks** [Mews-MIS/Mews-Client#9]
## IssueName
core - 공통 컴포넌트 - contentRow

## Description
컨텐트 한줄 표시 줄을 만든다.

## Todo
- [x] index 표시
- [x] 이미지가 있을시 이미지 표시
- [x] 이미지가 없으면 디폴트 표시
- [x] 제목표시
- [x] 제목이 길면 말줄임표로 제묵 줄이기
- [x] 클릭시 바로가기

## ETC
기타 참고사항
